'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';

type State={jobs:any[];approvals:any[];events:any[];agents:any[];factories:any[];products:any[];integrations:any[];readiness:Record<string,boolean>;serverTime?:string};
const EMPTY:State={jobs:[],approvals:[],events:[],agents:[],factories:[],products:[],integrations:[],readiness:{}};
const META:Record<string,{icon:string,sub:string,accent:string}>={
  solutions:{icon:'🧹',sub:'Lead → CRM → Outreach → Quote',accent:'#b56cff'},aces:{icon:'🚗',sub:'Inventory → Campaign → Lead → Sale',accent:'#79ff9d'},creator:{icon:'🖼️',sub:'Owned Photos → Products → Etsy',accent:'#53d8fb'},etsy:{icon:'🛍️',sub:'Draft → Files → Listing',accent:'#ffc857'},media:{icon:'🎬',sub:'Creative production',accent:'#ff7bbd'},assets:{icon:'🎮',sub:'Digital product forge',accent:'#8ea1ff'},command:{icon:'🧠',sub:'Routes and monitors work',accent:'#79ff9d'},analytics:{icon:'📊',sub:'Jobs, conversion and revenue',accent:'#63f5cf'}
};
function pct(j:any){return j.total_steps?Math.round((j.completed_steps/j.total_steps)*100):0}
export default function Home(){
  const [state,setState]=useState<State>(EMPTY);const [token,setToken]=useState('');const [selected,setSelected]=useState('command');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [tab,setTab]=useState<'city'|'jobs'|'approvals'|'creator'|'quote'|'integrations'>('city');
  useEffect(()=>{setToken(sessionStorage.getItem('abc_owner_token')||'')},[]);
  async function api(path:string,init:RequestInit={}){const headers=new Headers(init.headers);if(token)headers.set('x-owner-token',token);const r=await fetch(path,{...init,headers,cache:'no-store'});const j=await r.json().catch(()=>({}));if(!r.ok)throw new Error(j.error||`${r.status}`);return j}
  async function refresh(){try{setState(await api('/api/state'));setError('')}catch(e:any){setError(e.message)}}
  useEffect(()=>{if(token!==undefined){refresh();const id=setInterval(refresh,2500);return()=>clearInterval(id)}},[token]);
  async function dispatch(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const text=String(fd.get('command')||'').trim();if(!text)return;setBusy(true);try{const j=await api('/api/commands',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({text})});await api('/api/worker/tick',{method:'POST'}).catch(()=>null);(e.currentTarget as HTMLFormElement).reset();setSelected(j.factory);await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function tick(){setBusy(true);try{await api('/api/worker/tick',{method:'POST'});await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function decide(id:string,decision:'approved'|'rejected'){setBusy(true);try{await api(`/api/approvals/${id}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({decision})});if(decision==='approved')await api('/api/worker/tick',{method:'POST'}).catch(()=>null);await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function retry(id:string){setBusy(true);try{await api(`/api/jobs/${id}/retry`,{method:'POST'});await api('/api/worker/tick',{method:'POST'}).catch(()=>null);await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);try{const fd=new FormData(e.currentTarget);await api('/api/media/upload',{method:'POST',body:fd});await api('/api/worker/tick',{method:'POST'}).catch(()=>null);(e.currentTarget as HTMLFormElement).reset();setTab('jobs');await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  async function quote(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);const body:any={};for(const [k,v] of fd.entries())body[k]=Number(v);setBusy(true);try{const q=await api('/api/quotes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});alert(`Recommended monthly price: $${q.recommendedPrice.toFixed(2)}\nMonthly cost: $${q.monthlyCost.toFixed(2)}\nGross profit: $${q.grossProfit.toFixed(2)}`)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
  const selectedFactory=useMemo(()=>state.factories.find(f=>f.slug===selected),[state.factories,selected]);
  const selectedAgents=state.agents.filter(a=>a.factory_slug===selected);const selectedJobs=state.jobs.filter(j=>j.factory_slug===selected);
  const pending=state.approvals.filter(a=>a.status==='pending').length;
  return <main>
    <header className="top"><div><div className="eyebrow">AI BUSINESS CITY · PHASE 2 LIVE</div><h1>Factory Operations Control Plane</h1><p>Backend-authoritative jobs, approval gates and real provider adapters.</p></div><div className="topStats"><b>{state.jobs.length}</b><span>jobs</span><b>{pending}</b><span>approvals</span><b>{state.agents.filter(a=>a.status==='working').length}</b><span>working</span></div></header>
    <div className="tokenbar"><input value={token} onChange={e=>{setToken(e.target.value);sessionStorage.setItem('abc_owner_token',e.target.value)}} placeholder="Owner token (only needed when APP_OWNER_TOKEN is set)"/><button onClick={refresh}>Connect</button>{error&&<span className="error">{error}</span>}</div>
    <nav>{(['city','jobs','approvals','creator','quote','integrations'] as const).map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t.toUpperCase()}{t==='approvals'&&pending?` (${pending})`:''}</button>)}</nav>
    {tab==='city'&&<>
      <section className="cityLayout"><div className="city"><div className="roads r1"/><div className="roads r2"/>{state.factories.map((f:any)=>{const m=META[f.slug]||{icon:'🏭',sub:'Factory',accent:'#79ff9d'};const agents=state.agents.filter(a=>a.factory_slug===f.slug);const active=agents.filter(a=>a.status==='working').length;const wait=agents.filter(a=>a.status==='approval_required'||a.status==='waiting').length;return <button key={f.id} className="factory" style={{'--accent':m.accent} as any} onClick={()=>setSelected(f.slug)}><div className="roof"/><div className="building"><div className="factoryHead"><span>{m.icon}</span><b>{f.name}</b></div><small>{m.sub}</small><div className="workers">{agents.slice(0,9).map((a:any)=><i key={a.id} className={a.status==='error'?'red':a.status==='approval_required'||a.status==='waiting'?'amber':a.status==='working'?'green':'idle'} title={`${a.name}: ${a.status}`}/>)}</div><div className="factoryFoot"><span>{active} active</span><span>{wait} waiting</span></div></div></button>})}</div>
      <aside className="terminal"><div className="terminalHead"><div><span>FACTORY TERMINAL</span><h2>{selectedFactory?.name||'Command Tower'}</h2></div><em>{selected.toUpperCase()}</em></div><div className="metrics"><div><b>{selectedJobs.length}</b><span>Jobs</span></div><div><b>{selectedAgents.filter(a=>a.status==='working').length}</b><span>Working</span></div><div><b>{state.approvals.filter(a=>a.factory_slug===selected&&a.status==='pending').length}</b><span>Approval</span></div><div><b>{selectedJobs.filter(j=>j.status==='completed').length}</b><span>Complete</span></div></div><h3>AI Employees</h3>{selectedAgents.map((a:any)=><div className="employee" key={a.id}><i className={a.status==='error'?'red':a.status==='approval_required'||a.status==='waiting'?'amber':a.status==='working'?'green':'idle'}/><div><b>{a.name}</b><small>{a.role}</small></div><span>{a.status}</span></div>)}<h3>Recent Work</h3>{selectedJobs.slice(0,5).map((j:any)=><div className="miniJob" key={j.id}><b>{j.type}</b><span>{j.status}</span><div className="bar"><i style={{width:`${pct(j)}%`}}/></div></div>)}</aside></section>
      <section className="command"><form onSubmit={dispatch}><input name="command" placeholder="Find 20 medical practices in Plano and prepare outreach"/><button disabled={busy}>Dispatch</button></form><div className="quick"><button onClick={()=>{const f=document.querySelector<HTMLInputElement>('[name=command]');if(f)f.value='Find 20 medical practices in Plano and prepare outreach'}}>Solutions leads</button><button onClick={()=>{const f=document.querySelector<HTMLInputElement>('[name=command]');if(f)f.value='Create an ACES $1,500 down campaign for available economy vehicles and publish after approval'}}>ACES campaign</button><button onClick={tick} disabled={busy}>Run worker now</button></div></section>
      <section className="activity"><h2>Live Activity</h2>{state.events.slice(0,20).map((e:any)=><div key={e.id}><time>{new Date(e.created_at).toLocaleTimeString()}</time><b>{e.factory_slug||'system'}</b><span>{e.type}</span><small>{JSON.stringify(e.payload)}</small></div>)}</section>
    </>}
    {tab==='jobs'&&<section className="listPage"><h2>Jobs</h2>{state.jobs.map((j:any)=><article className="jobCard" key={j.id}><div><b>{j.factory_slug?.toUpperCase()} · {j.type}</b><p>{j.input_json?.text||j.id}</p><div className="bar"><i style={{width:`${pct(j)}%`}}/></div></div><div className="jobRight"><span className={`status ${j.status}`}>{j.status}</span>{['failed','waiting_dependency'].includes(j.status)&&<button onClick={()=>retry(j.id)}>Retry</button>}</div></article>)}</section>}
    {tab==='approvals'&&<section className="listPage"><h2>Approval Center</h2>{state.approvals.length===0&&<p>No approval requests yet.</p>}{state.approvals.map((a:any)=><article className="approval" key={a.id}><div><b>{a.action_type}</b><p>{a.factory_slug} · risk level {a.risk_level}</p><pre>{JSON.stringify(a.preview_json,null,2)}</pre></div><div><span className={`status ${a.status}`}>{a.status}</span>{a.status==='pending'&&<div className="actions"><button onClick={()=>decide(a.id,'approved')}>Approve</button><button className="danger" onClick={()=>decide(a.id,'rejected')}>Reject</button></div>}</div></article>)}</section>}
    {tab==='creator'&&<section className="creatorPage"><div className="formPanel"><h2>Creator Media Factory</h2><p>Upload an image you own or are licensed to use. The original is preserved and derivatives keep lineage.</p><form onSubmit={upload}><label>Owned photo<input type="file" name="file" accept="image/*" required/></label><label>Collection<select name="collection"><option value="faith">Faith + Identity</option><option value="business">Hustle + Business</option><option value="automotive">Automotive + Lifestyle</option><option value="mixed">Mixed</option></select></label><label>Notes<textarea name="notes" placeholder="What should the product line emphasize?"/></label><input type="hidden" name="rightsStatus" value="owner_supplied"/><button disabled={busy}>Upload & Start Factory</button></form></div><div className="products"><h2>Products</h2>{state.products.map((p:any)=><article key={p.id}><b>{p.name}</b><span>{p.qa_state} · {p.approval_state}</span><pre>{JSON.stringify(p.metadata,null,2)}</pre></article>)}</div></section>}
    {tab==='quote'&&<section className="formPanel quote"><h2>Solutions Quote Engine</h2><form onSubmit={quote}>{[['visitsPerMonth',4],['hoursPerVisit',4],['teamSize',2],['loadedHourlyRate',20],['supplies',150],['travel',100],['overhead',250],['targetMargin',0.35]].map(([name,value])=><label key={String(name)}>{String(name)}<input name={String(name)} type="number" step="0.01" defaultValue={String(value)} required/></label>)}<button>Calculate</button></form></section>}
    {tab==='integrations'&&<section className="integrationGrid">{Object.entries(state.readiness||{}).map(([k,v])=><article key={k}><b>{k.toUpperCase()}</b><span className={v?'ok':'off'}>{v?'READY':'NOT CONFIGURED'}</span><p>{integrationHelp(k)}</p></article>)}</section>}
  </main>
}
function integrationHelp(k:string){const map:Record<string,string>={openai:'Research, reasoning, media analysis and generation.',zoho:'Solutions CRM records and lead status.',google:'Gmail drafts and Calendar.',etsy:'Creator products → Etsy draft listings.',retell:'Approved outbound AI calls.',meta:'Approved ACES/social publishing.'};return map[k]||''}
